import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import TnrcNav from "@/components/TnrcNavbar/TnrcNav";
import Footer from "../components/Footer/Footer.jsx";

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <TnrcNav/>  
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  );
}
